// ─── main.dart ───────────────────────────────────────────────────────────────
//
// Entry point.  Initialises Firebase, then listens to auth state to decide
// whether to show LoginPage or DashboardPage — mirrors the React
// AuthProvider + conditional render in App.tsx.
// ─────────────────────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_service.dart';
import 'LoginPage.dart';
import 'DashboardPage.dart';

// ── Firebase options ─────────────────────────────────────────────────────────
// Generated by `firebase init` or `flutterfire configure`.
// Replace the placeholder values below with your actual project values
// from the Firebase Console (these match the JS config you provided).
class _FirebaseOptions {
  static FirebaseOptions get currentPlatform => web;

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvSwVUFKiQOUJNEqFuHp4O_o2mthRdCGM',
    authDomain: 'kasubook.firebaseapp.com',
    projectId: 'kasubook',
    storageBucket: 'kasubook.firebasestorage.app',
    messagingSenderId: '654865930698',
    appId: '1:654865930698:web:38f4cf7b65c3f7f56fd733',
    measurementId: 'G-G9HXP92JSD',
  );

  // TODO: Add Android / iOS options here once you run
  //       `flutterfire configure` — it will generate firebase_options.dart
  //       automatically with platform-specific configs.
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: _FirebaseOptions.currentPlatform);
  runApp(const KasuBookApp());
}

class KasuBookApp extends StatelessWidget {
  const KasuBookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'KasuBook',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        fontFamily: 'Roboto',
        scaffoldBackgroundColor: const Color(0xFFF9FAFB),
      ),
      // StreamBuilder on authStateChanges mirrors the React <AuthProvider>
      // conditional render: if user is null → Login, else → Dashboard.
      home: StreamBuilder(
        stream: FirebaseService().authStateStream,
        builder: (context, snapshot) {
          // Still waiting for the first auth event
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const _SplashScreen();
          }

          // User is logged in
          if (snapshot.hasData && snapshot.data != null) {
            return const DashboardPage();
          }

          // No user → login
          return const LoginPage();
        },
      ),
    );
  }
}

// ── Splash while Firebase initialises ───────────────────────────────────────
class _SplashScreen extends StatelessWidget {
  const _SplashScreen();

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF6366F1), Color(0xFFA855F7), Color(0xFFEC4899)],
        ),
      ),
      child: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.account_balance_wallet_rounded, color: Colors.white, size: 56),
            SizedBox(height: 16),
            Text('KasuBook', style: TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold)),
            SizedBox(height: 24),
            CircularProgressIndicator(color: Colors.white),
          ],
        ),
      ),
    );
  }
}